### ISSUE TITLE
`kubectl get machines` output formatting

### ISSUE THREAD

**Issue by pogzie** [some-things/dkp-mirror#3] opened 2022-02-21 08:30 UTC
`kubectl get machines` output is not formatted correctly. workaround would be to -oyaml it to be readable.

**Comment by some-things** [comment] 2022-02-26 21:21
Still looking into this, but I believe the issue is due to missing webhooks:
https://github.com/kubernetes-sigs/cluster-api/blob/release-1.0/config/crd/patches/webhook_in_machines.yaml#L8-L19

We remove the webhook configuration from the CRDs to avoid apiserver panics:
https://github.com/some-things/dkp-mirror/blob/40111cd1ab46ea1b0dd80f450ea46ed0b311f866/src/up/up.ts#L103-L111

Not sure if there will be an elegant solution if that is the case, but will dig more 👍  

It could also be related to the way `dkp-diagnose` generates the bundle resources. In the 1.x bundle, this kind of workflow was much more streamlined.

If all else fails, I'll add a few `kubectl` commands to the readme for common helpful outputs and/or add a subcommand for a quick diagnostic snapshot.

**Comment by some-things** [comment] 2022-08-03 02:14
This will be resolved in the next release.

**Closed as completed by some-things** 2022-08-03 02:14 UTC
